#!/usr/bin/perl

use strict;
use warnings;

use Template;

MAIN: {
    my $template = Template->new( {
        INCLUDE_PATH => '.',
    } );
    $template->process('assignment.tt', {
        form => {
            first_name => 'Andrew',
            last_name  => 'Korty',
            email1     => 'ninkasi@ajk.name',
            flight1 => 1,
            flight2 => 1,
        },
        title => 'Brewers Cup Judge Volunteer Confirmation',
        format => $ARGV[0],
    }) or die $template->error();
}
